Name: CSS ID
Description: This indicates which theme # to use. Default value is "". Valid values are any number for which there's a set of CSS theme files. The system fills in missing parts of themes with default "" CSS files.
Content: 