Name: CSS Colour Inversion
Description: This indicates whether to invert #[][][][][][] colours in detected CSS files. Default value is "False", which means no inversion. Valid values are "True", "False", or "" (equals FALSE).
Content: False