Name: Downloads URL
Description: This indicates the full URL of the website's downloads folder (e.g., "http://localhost/downloads"). Default value is "http://localhost/downloads". The domain doesn't need to be the same as the website URL if the file are being hosted elsewhere.
Content: http://localhost/downloads