Name: Downloads Folder Path
Description: This indicates the path, within the application root, to the downloads folder. The default value is "/www/public/downloads". Alternatively, a value like "/www/special/downloads" can be used to keep downloads seperate from the website, if they're going to be hosted on a CDN server.
Content: /www/public/downloads