Name: Parent URL
Description: This indicates the full URL of a parent website (e.g., "http://localhost/index.html"). The default value is "". A value of "" can be used, if there is no parent website (disables features which use this information).
Content: http://localhost/index.html