Name: Uploads Age Limit
Description: Specifies an age limit in days for uploads. Any uploads older than this, won't be copied to the downloads folder, though the site will still list them. Default value is "90". A value of "" means no limit.
Content: 