Name: Uploads Quantity Limit
Description: Specifies a quantity limit for uploads. This is the max number of eligible uploads copied to the downloads folder, though the site will still list them. The default value is "250". A value of "" means no limit.
Content: 15