Name: Landing CSS
Description: This contains content for the the file "/www/public/assets/landing.css".
Destination: /assets/landing.css
Content:
"
.banner {
	text-align: right;
}
.banner_image {
	max-height: 400px;
	min-height: 400px;
	width: auto;
}
.banner_statement {
	font-size: 56px;
	font-weight: bold;
	text-align: left;
	padding: 25px;
}
#banner_1 {
	background-color: #ffceec;
	color: #ec2aa1;
}
#banner_2 {
	background-color: #cef6ff;
	text-align: left;
	color: #25a8c6;
}
#banner_2 .banner_statement {
	text-align: right;
}
#banner_3 {
	background-color: #d2ffce;
	color: #34c428;
}
#banner_4 {
	background-color: #FFFFFF;
	text-align: center;
	color: #000000;
	font-size: 36px;
}
#banner_4 .banner_statement {
	text-align: center;
	font-size: 36px;
	padding-top: 100px;
}
#content_1_inner {
	min-width: 100%;
	max-width: 100%;
	margin: 0px;
	padding: 0px;
}
#content_1_outter {
	padding-top: 0px;
}
.headings_1 {
	display: none;
}
#header_2_outter {
	display: none;
}
#footer_3_outter {
	display: none;
}
#footer_4_outter {
	display: none;
}
"