Name: Link Pages CSS
Description: This contains content for the the file "/www/public/assets/link-pages.css".
Destination: /assets/link-pages.css
Content:
"
.link_holder {
	display: flex;
	align-items: center;
	gap: 15px;
}
.link_holder .link_content {
	margin-top: 0px;
}
.link_holder a {
	
}
.link_holder .link_icon {
	
}
"