Name: Link Pages 3 CSS
Description: This contains content for the the file "/www/public/assets/link-pages-3.css".
Destination: /assets/link-pages-3.css
Content:
"
.link_holder {
	color: #26343D;
}

.link_holder .link_content {
	color: #26343D;
}

.link_holder a:link {
	color: #426A8C;
}

.link_holder a:visited {
	color: #6B5F8C;
}

.link_holder a:hover {
	color: #6F94AE;
}

.link_holder a:active {
	color: #264A66;
}

"