Name: Post Pages 3 CSS
Description: This contains content for the the file "/www/public/assets/post-pages-3.css".
Destination: /assets/post-pages-3.css
Content:
"
.mu_h2_content {
	color: #253640;
}

.mu_label_text,
.mu_label_end {
	color: #253640;
}

.mu_image_content,
.mu_page_meta {
	color: #26343D;
}
"