Name: Upload Pages CSS
Description: This contains content for the the file "/www/public/assets/upload-pages.css".
Destination: /assets/upload-pages.css
Content:
"
.item_previews_image {
	min-width: 100%;
	max-width: 100%;
	padding-bottom: 15px;
}
.item_previews_text {
	background-color: #EEEEEE;
	padding: 15px;
	margin-bottom: 15px;
}
.item_previews_audio {
	min-width: 100%;
	max-width: 100%;
}
.item_previews_video {
	min-width: 100%;
	max-width: 100%;
}
.item_download_link_holder {
	margin-bottom: 15px;
}
.item_status_message {
	margin-bottom: 15px;
	color: #e10808;
}
"