Name: Robots
Description: This contains content for the the file "/www/public/robots.txt".
Destination: /robots.txt
Content:
"
User-agent: *
Disallow: /assets/
Disallow: /databases/
Disallow: /downloads/
"