Name: Navigation
Description: This contains content for the the file "/www/public/navigation-pages/navigation.html".
Destination: /navigation-pages/navigation.html
Content:
"
<div id='navlinks_pages_outter'>
<div id='navlinks_pages_inner'>
<h2>Pages</h2>
<a class='navlinks' data-relative-url="true" href="/index.html">Home</a>
<!-- Do not list landing page, because index page should be configured to redirect there if a site wishes to use it. -->
<a class='navlinks' data-relative-url="true" href="/widget-pages/browse.html?sb_mode=browse">Browse</a>
<a class='navlinks' data-relative-url="true" href="/widget-pages/search.html?sb_mode=search&sb_kmt=70">Search</a>
<a class='navlinks' data-relative-url="true" href="/regular-pages/about.html">About</a><!-- About is not a meta page, because it's about the site, or owner, as opposed to the setup -->
</div>
</div>
<div id='navlinks_meta_outter'>
<div id='navlinks_meta_inner'>
<h2>Meta</h2>
<a class='navlinks' data-relative-url="true" href="/regular-pages/legal.html">Legal</a>
<a class='navlinks' data-relative-url="true" href="/widget-pages/supported-systems.html">Supported Systems</a>
<a class='navlinks' data-relative-url="true" href="/widget-pages/statistics.html">Statistics</a>
<a class='navlinks' data-relative-url="true" href="/robots.txt">robots.txt</a>
<a class='navlinks' data-relative-url="true" href="/humans.txt">humans.txt</a>
<a class='navlinks' data-relative-url="true" href="/sitemap_index.xml">sitemap_index.xml</a>
<a class='navlinks' data-relative-url="true" href="/widget-pages/version.html">Version</a>
</div>
</div>
<div id='navlinks_tools_outter'>
<div id='navlinks_tools_inner'>
<h2>Tools</h2>
<a class='navlinks' data-relative-url="true" href="/widget-pages/brute-force.html">Brute Force</a>
</div>
</div>
<div id='navlinks_miscellaneous_outter'>
<div id='navlinks_miscellaneous_inner'>
<h2>Miscellaneous</h2>
<a class='navlinks' data-relative-url="true" href="/Hello World.txt">Hello World.txt</a>
</div>
</div>
<script>
window.onload = function(){
	if (document.referrer.startsWith(location.origin)){
		document.getElementById("navigation").style.display = 'inline-block';
		document.getElementById("navigation_button").href = document.referrer;
		document.getElementById("navigation_button").innerHTML = '&#9166; ';
	} else {
		var elem = document.getElementById("navigation");
		elem.remove();
	}
}
</script>
"