Name: Navigation
Description: This contains content for the the file "/www/public/navigation-pages/navigation.html".
Destination: /navigation-pages/navigation.html
Content:
"
<div id='navlinks_pages_outter'>
<div id='navlinks_pages_inner'>
<h2>Pages</h2>
<a class='navlinks' href="/index.html">Home</a>
<!-- Do not list landing page, because index page should be configured to redirect there if a site wishes to use it. -->
<a class='navlinks' href="/widget-pages/search-reverse-chronological/search-1.html">Search</a>
<a class='navlinks' href="/widget-pages/browse-reverse-chronological/browse-1.html?sb_item_types=su">Browse</a>
<a class='navlinks' href="/regular-pages/about.html">About</a>
<a class='navlinks' href="/regular-pages/legal.html">Legal</a>
<a class='navlinks' href="/widget-pages/supported-systems.html">Supported Systems</a>
</div>
</div>
<div id='navlinks_meta_outter'>
<div id='navlinks_meta_inner'>
<h2>Meta Pages/Files</h2>
<a class='navlinks' href="/robots.txt">robots.txt</a>
<a class='navlinks' href="/humans.txt">humans.txt</a>
<a class='navlinks' href="/sitemap.xml">sitemap.xml</a>
<a class='navlinks' href="/Hello World.txt">Hello World.txt</a>
<a class='navlinks' href="/widget-pages/statistics.html">Statistics</a>
<a class='navlinks' href="/widget-pages/version.html">Version</a>
</div>
</div>
<script>
window.onload = function(){
	if (document.referrer.startsWith(location.origin)){
		document.getElementById("navigation").style.display = 'inline-block';
		document.getElementById("navigation_button").href = document.referrer;
		document.getElementById("navigation_button").innerHTML = '&#9166; ';
	} else {
		var elem = document.getElementById("navigation");
		elem.remove();
	}
}
</script>
"