Name: About
Description: This contains content for the the file "/www/public/regular-pages/about.html".
Destination: /regular-pages/about.html
Content:
"
<h2>Overview</h2>
<p>This is a brief description of the person, company, or organization.</p>

<h2>History</h2>
<p>This delves into the history of the person, company, or organization</p>

<h2>Closing</h2>
<p>This provides summary.</p>
"