Name: Index
Description: This contains content for the the file "/www/public/index.html".
Destination: /index.html
Content:
"
<h1>Redirection</h1>
<div>You should be automatically redirected to the browsing page, before ever seeing this message. However, this can fail if Javascript is disabled in your browser. You might also see this message if the page loaded slowly. Click <a id="redirection_link" href="/widget-pages/browse-reverse-chronological/browse-1.html?sb_item_types=su">here</a> to manually redirect yourself.</div>
<script>
// Using "/regular-pages/landing.html" might be preferrable for a business website instead of "/widget-pages/browse-reverse-chronological/browse-1.html"
function fun_be180b43_for_event_i1_v1() {
    var var_be180b43_link_el_str = document.getElementById("redirection_link");
    if (var_be180b43_link_el_str !== null) {
        var_be180b43_link_str = var_da1cdfc8_url_gstr + var_be180b43_link_el_str.getAttribute("href"); // "var_da1cdfc8_url_gstr" is from global-variables.js. "fun_9f3a7c2e_redirect_to_url_i1_v1" is from global.js
	fun_9f3a7c2e_redirect_to_url_i1_v1(var_be180b43_link_str);
    }
}
document.addEventListener("DOMContentLoaded", fun_be180b43_for_event_i1_v1);
</script>
"