Name: Landing
Description: This contains content for the the file "/www/public/regular-pages/landing.html". This page isn't needed for all sites, but some may prefer to make index.html point here, rather than to browse.html.
Destination: /regular-pages/landing.html
Content:
"
<div class='banner' id='banner_1'>
<!-- Music That Moves You -->
<div class='banner_statement'>Things that move you.</div>
<img class='banner_image' data-relative-url="true" src="/assets/Landing Banner - Music v1.png" alt="Banner 1">
</div>

<div class='banner' id='banner_2'>
<!-- Tools Which Empower You -->
<div class='banner_statement'>Things which empower you.</div>
<img class='banner_image' data-relative-url="true" src="/assets/Landing Banner - Productive v2.png" alt="Banner 2">
</div>

<div class='banner' id='banner_3'>
<!-- Photos To Inspire You -->
<div class='banner_statement'>Things to inspire you.</div>
<img class='banner_image' data-relative-url="true" src="/assets/Landing Banner - Thinking v1.png" alt="Banner 3">
</div>

<div class='banner' id='banner_4'>
<!-- Start Browsing -->
<div class='banner_statement'><a data-relative-url="true" href="/widget-pages/browse-reverse-chronological/browse-1.html?item_types=status+update">Start Browsing</a> to discover everything we have to offer.</div>
<img class='banner_image' data-relative-url="true" src="/assets/Landing Banner - Phone 2 v2.png" alt="Banner 4">
</div>
"